//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Euler.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37107287533902102798797998220837590246510135740250
        ///46376937677490009712648124896970078050417018260538
        ///74324986199524741059474233309513058123726617309629
        ///91942213363574161572522430563301811072406154908250
        ///23067588207539346171171980310421047513778063246676
        ///89261670696623633820136378418383684178734361726757
        ///28112879812849979408065481931592621691275889832738
        ///44274228917432520321923589422876796487670272189318
        ///47451445736001306439091167216856844588711603153276
        ///70386486105843025439939619828917593665686757 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string problem13 {
            get {
                return ResourceManager.GetString("problem13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75
        ///95 64
        ///17 47 82
        ///18 35 87 10
        ///20 04 82 47 65
        ///19 01 23 75 03 34
        ///88 02 77 73 07 63 67
        ///99 65 04 28 06 16 70 92
        ///41 41 26 56 83 40 80 70 33
        ///41 48 72 33 47 32 37 16 94 29
        ///53 71 44 65 25 43 91 52 97 51 14
        ///70 11 33 28 77 73 17 78 39 68 17 57
        ///91 71 52 38 17 14 91 43 58 50 27 29 48
        ///63 66 04 68 89 53 67 30 73 16 69 87 40 31
        ///04 62 98 27 23 09 70 98 73 93 38 53 60 04 23.
        /// </summary>
        internal static string problem18 {
            get {
                return ResourceManager.GetString("problem18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3
        ///7 4
        ///2 4 6
        ///8 5 9 188.
        /// </summary>
        internal static string problem18Test {
            get {
                return ResourceManager.GetString("problem18Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;MARY&quot;,&quot;PATRICIA&quot;,&quot;LINDA&quot;,&quot;BARBARA&quot;,&quot;ELIZABETH&quot;,&quot;JENNIFER&quot;,&quot;MARIA&quot;,&quot;SUSAN&quot;,&quot;MARGARET&quot;,&quot;DOROTHY&quot;,&quot;LISA&quot;,&quot;NANCY&quot;,&quot;KAREN&quot;,&quot;BETTY&quot;,&quot;HELEN&quot;,&quot;SANDRA&quot;,&quot;DONNA&quot;,&quot;CAROL&quot;,&quot;RUTH&quot;,&quot;SHARON&quot;,&quot;MICHELLE&quot;,&quot;LAURA&quot;,&quot;SARAH&quot;,&quot;KIMBERLY&quot;,&quot;DEBORAH&quot;,&quot;JESSICA&quot;,&quot;SHIRLEY&quot;,&quot;CYNTHIA&quot;,&quot;ANGELA&quot;,&quot;MELISSA&quot;,&quot;BRENDA&quot;,&quot;AMY&quot;,&quot;ANNA&quot;,&quot;REBECCA&quot;,&quot;VIRGINIA&quot;,&quot;KATHLEEN&quot;,&quot;PAMELA&quot;,&quot;MARTHA&quot;,&quot;DEBRA&quot;,&quot;AMANDA&quot;,&quot;STEPHANIE&quot;,&quot;CAROLYN&quot;,&quot;CHRISTINE&quot;,&quot;MARIE&quot;,&quot;JANET&quot;,&quot;CATHERINE&quot;,&quot;FRANCES&quot;,&quot;ANN&quot;,&quot;JOYCE&quot;,&quot;DIANE&quot;,&quot;ALICE&quot;,&quot;JULIE&quot;,&quot;HEATHER&quot;,&quot;TER....
        /// </summary>
        internal static string problem22 {
            get {
                return ResourceManager.GetString("problem22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,ABILITY,ABLE,ABOUT,ABOVE,ABSENCE,ABSOLUTELY,ACADEMIC,ACCEPT,ACCESS,ACCIDENT,ACCOMPANY,ACCORDING,ACCOUNT,ACHIEVE,ACHIEVEMENT,ACID,ACQUIRE,ACROSS,ACT,ACTION,ACTIVE,ACTIVITY,ACTUAL,ACTUALLY,ADD,ADDITION,ADDITIONAL,ADDRESS,ADMINISTRATION,ADMIT,ADOPT,ADULT,ADVANCE,ADVANTAGE,ADVICE,ADVISE,AFFAIR,AFFECT,AFFORD,AFRAID,AFTER,AFTERNOON,AFTERWARDS,AGAIN,AGAINST,AGE,AGENCY,AGENT,AGO,AGREE,AGREEMENT,AHEAD,AID,AIM,AIR,AIRCRAFT,ALL,ALLOW,ALMOST,ALONE,ALONG,ALREADY,ALRIGHT,ALSO,ALTERNATIVE,ALTHOUGH,ALWAYS,AMONG,AMONGST,A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem42 {
            get {
                return ResourceManager.GetString("Problem42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59
        ///73 41
        ///52 40 09
        ///26 53 06 34
        ///10 51 87 86 81
        ///61 95 66 57 25 68
        ///90 81 80 38 92 67 73
        ///30 28 51 76 81 18 75 44
        ///84 14 95 87 62 81 17 78 58
        ///21 46 71 58 02 79 62 39 31 09
        ///56 34 35 53 78 31 81 18 90 93 15
        ///78 53 04 21 84 93 32 13 97 11 37 51
        ///45 03 81 79 05 18 78 86 13 30 63 99 95
        ///39 87 96 28 03 38 42 17 82 87 58 07 22 57
        ///06 17 51 17 07 93 09 07 75 97 95 78 87 08 53
        ///67 66 59 60 88 99 94 65 55 77 55 34 27 53 78 28
        ///76 40 41 04 87 16 09 42 75 69 23 97 30 60 10 79 87
        ///12 10 44 26 21 36 32 84 98 60 13 12  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string problem67 {
            get {
                return ResourceManager.GetString("problem67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -340,495,-153,-910,835,-947
        ///-175,41,-421,-714,574,-645
        ///-547,712,-352,579,951,-786
        ///419,-864,-83,650,-399,171
        ///-429,-89,-357,-930,296,-29
        ///-734,-702,823,-745,-684,-62
        ///-971,762,925,-776,-663,-157
        ///162,570,628,485,-807,-896
        ///641,91,-65,700,887,759
        ///215,-496,46,-931,422,-30
        ///-119,359,668,-609,-358,-494
        ///440,929,968,214,760,-857
        ///-700,785,838,29,-216,411
        ///-770,-458,-325,-53,-505,633
        ///-752,-805,349,776,-799,687
        ///323,5,561,-36,919,-560
        ///-907,358,264,320,204,274
        ///-728,-466,350,969,292,-345
        ///940,836,272,-533,748, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string triangles {
            get {
                return ResourceManager.GetString("triangles", resourceCulture);
            }
        }
    }
}
